name: Deploy .NET App to Azure App Service (Prod)

on:
  push:
    branches: [ "master" ]
    workflow_dispatch: {}

env:
  AZURE_WEBAPP_NAME: wp1-17370703-fa25     # replace <student> with actual id
  DOTNET_VERSION: '8.0.x'
  PUBLISH_DIR: './publish'
  PROJECT_PATH: 'GitHubActions/GitHubActions.csproj'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish .NET app
        run: dotnet publish -c Release -o ${{ env.PUBLISH_DIR }}

      - name: Azure Login (client secret)
        uses: azure/login@v2
        with:
    creds: |
      {
        "clientId":       "${{ secrets.AZURE_CLIENT_ID }}",
        "clientSecret":   "${{ secrets.AZURE_CLIENT_SECRET }}",
        "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
        "tenantId":       "${{ secrets.AZURE_TENANT_ID }}"
      }

      - name: Deploy to Azure Web App (Production)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.PUBLISH_DIR }}